/******************************************************************************/
/*            Generated by IBExpert 2009.01.16 23/02/2012 10:06:29            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'admin-pc:C:\Vastus\Dados\BASE_PRI.GDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CLIENTES (
    CLI_CODIGO          INTEGER NOT NULL,
    CLI_TIPO            VARCHAR(1),
    CLI_NOME            VARCHAR(50),
    APELIDO             VARCHAR(50),
    CLI_CADASTRO        TIMESTAMP,
    TIP_CODIGO          VARCHAR(3),
    TIPO_PESSOA         VARCHAR(1),
    CPF                 VARCHAR(11),
    DOCUMENTO           VARCHAR(20),
    SEXO                VARCHAR(1),
    NASCIMENTO          VARCHAR(8),
    CNPJ                VARCHAR(14),
    INSCRICAO_ESTADUAL  VARCHAR(18),
    ATI_CODIGO          SMALLINT,
    ENDERECO            VARCHAR(50),
    BAIRRO              VARCHAR(20),
    CIDADE              VARCHAR(20),
    UF                  VARCHAR(2),
    CEP                 VARCHAR(8),
    TELEFONE_1          VARCHAR(11),
    TELEFONE_2          VARCHAR(11),
    FAX_1               VARCHAR(11),
    CELULAR_1           VARCHAR(11),
    OBSERVACAO          BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    ULTIMA_OPERACAO     TIMESTAMP,
    ULTIMO_VALOR        DOUBLE PRECISION,
    CLI_EMAIL           VARCHAR(50),
    CLI_SITE            VARCHAR(80),
    PAR_PARAMETRO       SMALLINT,
    CLI_BLOQUEADO       VARCHAR(1),
    CLI_CREDITO         DOUBLE PRECISION,
    CLI_CTPS            VARCHAR(15),
    CLI_TITULO          VARCHAR(15),
    CLI_NATURAL         VARCHAR(30),
    CLI_PAI             VARCHAR(40),
    CLI_MAE             VARCHAR(40),
    ESTADO_CIVIL        VARCHAR(1),
    CONJUGE             VARCHAR(40),
    CLI_CPF_CONJ        VARCHAR(11),
    CLI_DOC_CONJ        VARCHAR(15),
    CLI_NASC_CONJ       VARCHAR(8),
    CLI_LOCAL_TRAB      VARCHAR(40),
    CLI_END_TRAB        VARCHAR(40),
    CLI_FON_TRAB_1      VARCHAR(11),
    CLI_RAMAL_TRAB_1    SMALLINT,
    CLI_FON_TRAB_2      VARCHAR(11),
    CLI_TOTAL_COMPRA    DOUBLE PRECISION,
    CLI_QTDE_COMPRAS    INTEGER,
    ECF_TOTAL_ITENS     DOUBLE PRECISION,
    CLI_DIA_ANIV        VARCHAR(2),
    CLI_MES_ANIV        VARCHAR(2),
    COBRANCA            VARCHAR(1),
    ENDERECO_COB        VARCHAR(50),
    BAIRRO_COB          VARCHAR(20),
    CIDADE_COB          VARCHAR(20),
    UF_COB              VARCHAR(2),
    CEP_COB             VARCHAR(8),
    TELEFONE_1_COB      VARCHAR(12),
    TELEFONE_2_COB      VARCHAR(12)
);




/******************************************************************************/
/*                                Primary Keys                                */
/******************************************************************************/

ALTER TABLE CLIENTES ADD CONSTRAINT ICLIENTES PRIMARY KEY (CLI_CODIGO);


/******************************************************************************/
/*                                  Indices                                   */
/******************************************************************************/

CREATE INDEX ICLIENTES0 ON CLIENTES (CLI_CODIGO);
